use std::fs;
use std::path::PathBuf;

/// Stable substring stamped into the plugin's file path so `is_ours` can find
/// our entry in the user's `"plugin"` array regardless of exact path, mirrors
/// `ingest.rs`'s `MARKER` for the Claude hook command string.
const MARKER: &str = "logic-loop-opencode-plugin";

/// Bump when the plugin's translated payload shape changes in a way a reader
/// must know about, same role as `ingest.rs`'s `HOOK_VERSION`.
const OPENCODE_PLUGIN_VERSION: u32 = 1;

fn home() -> String {
    std::env::var("HOME").unwrap_or_else(|_| "/tmp".into())
}

/// OpenCode resolves its global config dir from `$XDG_CONFIG_HOME` or
/// `~/.config` on every platform, including Windows — no per-OS branch.
/// Matched here so we write to the same file OpenCode itself reads.
fn config_dir() -> PathBuf {
    match std::env::var("XDG_CONFIG_HOME") {
        Ok(v) if !v.is_empty() => PathBuf::from(v).join("opencode"),
        _ => PathBuf::from(home()).join(".config").join("opencode"),
    }
}

fn settings_path() -> PathBuf {
    config_dir().join("opencode.json")
}

fn plugin_path() -> PathBuf {
    PathBuf::from(home())
        .join(".context-terminal")
        .join(format!("{MARKER}.mjs"))
}

fn plugin_file_url() -> String {
    format!("file://{}", plugin_path().display())
}

/// The plugin module. Translates OpenCode's native plugin events into the
/// same `hook_event_name` wire shape Claude's shell hook already POSTs to
/// `/event` (see `ingest.rs`) — nothing downstream needs to know OpenCode
/// exists. Regenerated on every `opencode_hooks_setup` call so a version
/// bump redeploys it.
///
/// Field extraction for the generic `event` stream (session.created/
/// session.idle/permission.asked) is defensive: OpenCode's docs list the
/// event *names* but not a locked payload schema, so this tries a few
/// plausible paths and silently skips posting if none match rather than
/// guessing wrong and shipping a malformed row. Verify against a live run
/// (PLAN.md Phase 8 step 3) and tighten once the real shape is confirmed.
fn plugin_source() -> String {
    format!(
        r#"// Logic Loop OpenCode adapter — auto-generated by the app, do not edit by hand.
// Regenerated every time the OpenCode toggle is switched on. version {OPENCODE_PLUGIN_VERSION}
import {{ readFileSync }} from "node:fs";
import {{ homedir }} from "node:os";
import {{ join }} from "node:path";

const VERSION = {OPENCODE_PLUGIN_VERSION};

function loadIngestEnv() {{
  try {{
    const raw = readFileSync(join(homedir(), ".context-terminal", "ingest.env"), "utf8");
    const env = {{}};
    for (const line of raw.split("\n")) {{
      const i = line.indexOf("=");
      if (i > 0) env[line.slice(0, i)] = line.slice(i + 1).trim();
    }}
    return env.CT_PORT && env.CT_TOKEN ? env : null;
  }} catch {{
    return null;
  }}
}}

function sessionIdOf(props) {{
  return props?.sessionID ?? props?.info?.sessionID ?? props?.info?.id ?? props?.session?.id ?? null;
}}

const EVENT_MAP = {{
  "session.created": "SessionStart",
  "session.idle": "Stop",
  "permission.asked": "Notification",
}};

export const LogicLoopAdapter = async ({{ directory }}) => {{
  const ingest = loadIngestEnv();
  const tabId = process.env.LOGIC_LOOP_TAB_ID ?? "";

  // Fire-and-forget, always. A stalled or absent ingest server must never
  // delay the user's actual opencode session — this hook runs in-process,
  // unlike Claude's detached curl, so an accidental await here is a real
  // stall risk, not just a lost event.
  function post(payload) {{
    if (!ingest) return;
    try {{
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 2000);
      fetch(`http://127.0.0.1:${{ingest.CT_PORT}}/event`, {{
        method: "POST",
        headers: {{
          Authorization: `Bearer ${{ingest.CT_TOKEN}}`,
          "X-Logic-Loop-Tab": tabId,
          "X-Logic-Loop-Hook": String(VERSION),
          "Content-Type": "application/json",
        }},
        body: JSON.stringify(payload),
        signal: controller.signal,
      }})
        .catch(() => {{}})
        .finally(() => clearTimeout(timeout));
    }} catch {{
      // never let a translation/network error touch the user's session
    }}
  }}

  return {{
    event: async ({{ event }}) => {{
      try {{
        const hookName = EVENT_MAP[event?.type];
        if (!hookName) return;
        const sessionId = sessionIdOf(event.properties);
        if (!sessionId) return;
        post({{ hook_event_name: hookName, session_id: sessionId, cwd: directory }});
      }} catch {{
        // fail open — a bad event shape must never throw into opencode
      }}
    }},
    "chat.message": async (input) => {{
      try {{
        if (!input?.sessionID) return;
        post({{ hook_event_name: "UserPromptSubmit", session_id: input.sessionID, cwd: directory }});
      }} catch {{
        // fail open
      }}
    }},
    "tool.execute.after": async (input, output) => {{
      try {{
        if (!input?.sessionID) return;
        post({{
          hook_event_name: "PostToolUse",
          session_id: input.sessionID,
          cwd: directory,
          tool_name: input.tool,
          tool_input: input.args,
          tool_response: output,
        }});
      }} catch {{
        // fail open
      }}
    }},
  }};
}};

export default LogicLoopAdapter;
"#
    )
}

fn read_settings() -> Result<serde_json::Value, String> {
    match fs::read_to_string(settings_path()) {
        Ok(s) => serde_json::from_str(&s).map_err(|e| format!("opencode.json is not valid JSON: {e}")),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(serde_json::json!({})),
        Err(e) => Err(e.to_string()),
    }
}

fn write_settings(v: &serde_json::Value) -> Result<(), String> {
    let path = settings_path();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let pretty = serde_json::to_string_pretty(v).map_err(|e| e.to_string())?;
    fs::write(path, pretty + "\n").map_err(|e| e.to_string())
}

fn is_ours(entry: &serde_json::Value) -> bool {
    match entry {
        serde_json::Value::String(s) => s.contains(MARKER),
        serde_json::Value::Array(tuple) => tuple.first().is_some_and(is_ours),
        _ => false,
    }
}

fn strip_ours(settings: &mut serde_json::Value) {
    let Some(obj) = settings.as_object_mut() else {
        return;
    };
    let Some(arr) = obj.get_mut("plugin").and_then(|v| v.as_array_mut()) else {
        return;
    };
    arr.retain(|e| !is_ours(e));
    if arr.is_empty() {
        obj.remove("plugin");
    }
}

fn apply_setup(settings: &mut serde_json::Value) -> Result<(), String> {
    strip_ours(settings);
    if !settings.is_object() {
        *settings = serde_json::json!({});
    }
    let obj = settings.as_object_mut().ok_or("settings not an object")?;
    obj.entry("plugin")
        .or_insert_with(|| serde_json::json!([]))
        .as_array_mut()
        .ok_or("plugin is not an array")?
        .push(serde_json::Value::String(plugin_file_url()));
    Ok(())
}

#[tauri::command]
pub fn opencode_detect() -> bool {
    let Ok(path_var) = std::env::var("PATH") else {
        return false;
    };
    std::env::split_paths(&path_var).any(|dir| {
        let candidate = dir.join("opencode");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::metadata(&candidate).is_ok_and(|m| m.is_file() && m.permissions().mode() & 0o111 != 0)
        }
        #[cfg(not(unix))]
        {
            candidate.is_file()
        }
    })
}

#[tauri::command]
pub fn opencode_hooks_setup() -> Result<(), String> {
    let dir = PathBuf::from(home()).join(".context-terminal");
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    fs::write(plugin_path(), plugin_source()).map_err(|e| e.to_string())?;
    let mut settings = read_settings()?;
    apply_setup(&mut settings)?;
    write_settings(&settings)
}

#[tauri::command]
pub fn opencode_hooks_remove() -> Result<(), String> {
    let mut settings = read_settings()?;
    strip_ours(&mut settings);
    write_settings(&settings)
}

#[tauri::command]
pub fn opencode_hooks_status() -> Result<bool, String> {
    let settings = read_settings()?;
    Ok(settings
        .get("plugin")
        .and_then(|v| v.as_array())
        .is_some_and(|arr| arr.iter().any(is_ours)))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn foreign_settings() -> serde_json::Value {
        serde_json::json!({
            "model": "anthropic/claude-sonnet-4-6",
            "plugin": ["opencode-gemini-auth", ["opencode-bar", { "option": "value" }]]
        })
    }

    #[test]
    fn setup_is_idempotent_and_preserves_foreign_plugins() {
        let mut s = foreign_settings();
        apply_setup(&mut s).unwrap();
        let once = s.clone();
        apply_setup(&mut s).unwrap();
        assert_eq!(s, once, "second setup must not duplicate our entry");
        assert_eq!(s["plugin"][0], "opencode-gemini-auth");
        assert_eq!(s["plugin"][1][0], "opencode-bar");
        assert!(s["plugin"]
            .as_array()
            .unwrap()
            .iter()
            .any(|e| e.as_str().is_some_and(|s| s.contains(MARKER))));
    }

    #[test]
    fn remove_restores_foreign_settings_byte_identical() {
        let original = foreign_settings();
        let mut s = original.clone();
        apply_setup(&mut s).unwrap();
        strip_ours(&mut s);
        assert_eq!(s, original, "remove must fully restore pre-install state");
    }

    #[test]
    fn remove_on_never_installed_settings_is_a_noop() {
        let original = foreign_settings();
        let mut s = original.clone();
        strip_ours(&mut s);
        assert_eq!(s, original);
    }

    #[test]
    fn setup_on_empty_settings_creates_plugin_array() {
        let mut s = serde_json::json!({});
        apply_setup(&mut s).unwrap();
        assert_eq!(s["plugin"].as_array().unwrap().len(), 1);
    }

    #[test]
    fn plugin_source_embeds_the_version_and_ingest_contract() {
        let src = plugin_source();
        assert!(src.contains(&format!("version {OPENCODE_PLUGIN_VERSION}")));
        assert!(src.contains("X-Logic-Loop-Tab"));
        assert!(src.contains("LOGIC_LOOP_TAB_ID"));
        assert!(src.contains("ingest.env"));
    }
}
