use crate::home::home_or_tmp;
use std::fs;
use std::path::{Path, PathBuf};

/// Stamped into the generated file's header comment so `is_ours` can tell our
/// file apart from an unrelated user extension that happens to share the
/// `logic-loop.ts` filename. Mirrors `opencode.rs`'s `MARKER` and
/// `ingest.rs`'s hook-command `MARKER`.
const MARKER: &str = "logic-loop-pi-extension";

/// Bump when the generated extension's translated payload shape changes in a
/// way a reader must know about. `pi_hooks_status` only reports "on" for a
/// file stamped with the current version, same role as `ingest.rs`'s
/// `HOOK_VERSION` and `opencode.rs`'s `OPENCODE_PLUGIN_VERSION`.
const PI_EXTENSION_VERSION: u32 = 2;

/// Pi's documented global extension directory — files dropped here load
/// automatically with no settings.json entry and no per-project trust
/// prompt (confirmed live, Plan 026 Step 0: a probe file placed here loaded
/// on the next `pi` invocation with no `-e` flag and no `--approve`).
fn extensions_dir() -> PathBuf {
    PathBuf::from(home_or_tmp())
        .join(".pi")
        .join("agent")
        .join("extensions")
}

fn extension_path() -> PathBuf {
    extensions_dir().join("logic-loop.ts")
}

/// The generated extension source. Translates Pi's lifecycle events into the
/// same `hook_event_name` wire shape Claude's shell hook already POSTs to
/// `/event` (see `ingest.rs`) — nothing downstream needs to know Pi exists.
/// Regenerated on every `pi_hooks_setup` call so a version bump redeploys
/// it. Modeled on `opencode.rs`'s `plugin_source()`: ingest.env is re-read
/// per POST (not cached at extension load) so an app restart rotating the
/// port/token doesn't need a Pi `/reload`; POSTs are fire-and-forget with a
/// short abort timeout and swallowed errors, never awaited from inside a
/// lifecycle handler, so a stalled or absent ingest server can never delay
/// the user's actual Pi session. Only allowlisted fields are ever sent —
/// finalized visible user/assistant text plus bounded tool metadata, never
/// reasoning, tool result text, or a full message/session object.
///
/// Event shapes and the `read`/`bash`/`write` tool arg key names
/// (`path`, `command`) below are confirmed live against Pi 0.85.1
/// (Plan 026 Step 0 spike, `docs/TESTING.md` §53), not just upstream docs.
fn extension_source() -> String {
    format!(
        r#"// Logic Loop Pi adapter — auto-generated by the app, do not edit by hand.
// Regenerated every time the Pi toggle is switched on. {MARKER} version {PI_EXTENSION_VERSION}
import {{ readFileSync }} from "node:fs";
import {{ homedir }} from "node:os";
import {{ join }} from "node:path";

const VERSION = {PI_EXTENSION_VERSION};

function loadIngestEnv() {{
  try {{
    const raw = readFileSync(join(homedir(), ".context-terminal", "ingest.env"), "utf8");
    const env = {{}};
    for (const line of raw.split("\n")) {{
      const i = line.indexOf("=");
      if (i > 0) env[line.slice(0, i)] = line.slice(i + 1).trim();
    }}
    return env.CT_PORT && env.CT_TOKEN ? env : null;
  }} catch {{
    return null;
  }}
}}

// Only these three fields ever leave the process as tool_input — never a
// raw args passthrough, and never anything derived from a tool's result.
function normalizeToolArgs(args) {{
  const out = {{}};
  const pick = (canonical, aliases) => {{
    for (const key of aliases) {{
      if (typeof args?.[key] === "string") {{
        out[canonical] = args[key];
        return;
      }}
    }}
  }};
  pick("command", ["command"]);
  pick("file_path", ["path", "file_path"]);
  pick("description", ["description"]);
  return out;
}}

// Pi 0.85.1 live contract (Plan 039 Step 0): message_end fires once for
// every finalized user/assistant/toolResult message. Assistant tool-call
// rounds also end messages, but those contain only toolCall blocks. Reduce
// the finalized message to visible text blocks only; reasoning, tool calls,
// tool results, images, and future block types never leave the process.
function visibleMessage(message) {{
  if (message?.role !== "user" && message?.role !== "assistant") return null;
  if (!Array.isArray(message.content)) return null;
  const text = message.content
    .filter((block) => block?.type === "text" && typeof block.text === "string")
    .map((block) => block.text)
    .join("\n");
  if (!text.trim()) return null;
  return {{ role: message.role, text }};
}}

export default function (pi) {{
  const tabId = process.env.LOGIC_LOOP_TAB_ID ?? "";
  // toolCallId -> normalized args, captured at tool_execution_start and
  // consumed at tool_execution_end. Cleared on session_start/shutdown so a
  // call that never resolves can't leak across sessions in the same process.
  const pendingTools = new Map();

  // Fire-and-forget, always. This extension runs in-process, unlike
  // Claude's detached curl hook, so an accidental await here is a real
  // stall risk to the user's session, not just a lost event.
  function post(payload) {{
    const ingest = loadIngestEnv();
    if (!ingest) return;
    try {{
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 2000);
      fetch(`http://127.0.0.1:${{ingest.CT_PORT}}/event`, {{
        method: "POST",
        headers: {{
          Authorization: `Bearer ${{ingest.CT_TOKEN}}`,
          "X-Logic-Loop-Tab": tabId,
          "X-Logic-Loop-Hook": String(VERSION),
          "X-Logic-Loop-Agent": "pi",
          "Content-Type": "application/json",
        }},
        body: JSON.stringify(payload),
        signal: controller.signal,
      }})
        .catch(() => {{}})
        .finally(() => clearTimeout(timeout));
    }} catch {{
      // never let a translation/network error touch the user's session
    }}
  }}

  // session_id/cwd come from ctx fresh on every call rather than a closure
  // captured once at session_start, since a single long-lived interactive
  // process can carry multiple session_start events (/new, /resume, /fork).
  function rowBase(ctx) {{
    const sessionId = ctx?.sessionManager?.getSessionId?.();
    const cwd = ctx?.cwd;
    if (!sessionId || !cwd) return null;
    return {{ session_id: sessionId, cwd }};
  }}

  pi.on("session_start", async (_event, ctx) => {{
    try {{
      pendingTools.clear();
      const base = rowBase(ctx);
      if (!base) return;
      post({{ hook_event_name: "SessionStart", ...base }});
    }} catch {{
      // fail open
    }}
  }});

  pi.on("before_agent_start", async (_event, ctx) => {{
    try {{
      const base = rowBase(ctx);
      if (!base) return;
      post({{ hook_event_name: "UserPromptSubmit", ...base }});
    }} catch {{
      // fail open
    }}
  }});

  pi.on("message_end", async (event, ctx) => {{
    try {{
      const base = rowBase(ctx);
      const message = visibleMessage(event?.message);
      if (!base || !message) return;
      post({{
        hook_event_name: "TranscriptLine",
        ...base,
        line: JSON.stringify({{ type: "pi_message", ...message }}),
      }});
    }} catch {{
      // fail open; returning nothing also guarantees observation only
    }}
  }});

  pi.on("tool_execution_start", async (event) => {{
    try {{
      if (!event?.toolCallId) return;
      pendingTools.set(event.toolCallId, normalizeToolArgs(event.args));
    }} catch {{
      // fail open
    }}
  }});

  pi.on("tool_execution_end", async (event, ctx) => {{
    try {{
      const base = rowBase(ctx);
      const toolInput = pendingTools.get(event?.toolCallId) ?? {{}};
      pendingTools.delete(event?.toolCallId);
      if (!base || !event?.toolCallId) return;
      post({{
        hook_event_name: "PostToolUse",
        ...base,
        tool_use_id: event.toolCallId,
        tool_name: event.toolName,
        tool_input: toolInput,
        tool_response: {{ is_error: !!event.isError }},
      }});
    }} catch {{
      // fail open
    }}
  }});

  pi.on("agent_settled", async (_event, ctx) => {{
    try {{
      const base = rowBase(ctx);
      if (!base) return;
      post({{ hook_event_name: "Stop", ...base }});
    }} catch {{
      // fail open
    }}
  }});

  pi.on("session_shutdown", async () => {{
    pendingTools.clear();
  }});
}}
"#
    )
}

fn is_ours(source: &str) -> bool {
    source.contains(MARKER)
}

fn has_current_version(source: &str) -> bool {
    source.contains(&format!("version {PI_EXTENSION_VERSION}"))
}

/// Pure decision: what to write for `logic-loop.ts` given its current
/// content (`None` if absent). Refuses a file that exists but isn't ours.
fn plan_setup(existing: Option<&str>) -> Result<String, String> {
    if let Some(source) = existing {
        if !is_ours(source) {
            return Err("logic-loop.ts already exists and isn't a Logic Loop file — leaving it untouched".to_string());
        }
    }
    Ok(extension_source())
}

/// Pure decision: whether to delete `logic-loop.ts` given its current
/// content. `Ok(false)` covers both "absent" and "nothing to do"; `Err`
/// means a foreign file is in the way and must be left alone.
fn plan_remove(existing: Option<&str>) -> Result<bool, String> {
    match existing {
        None => Ok(false),
        Some(source) if is_ours(source) => Ok(true),
        Some(_) => Err("logic-loop.ts isn't a Logic Loop file — leaving it untouched".to_string()),
    }
}

fn is_executable(candidate: &std::path::Path) -> bool {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::metadata(candidate).is_ok_and(|m| m.is_file() && m.permissions().mode() & 0o111 != 0)
    }
    #[cfg(not(unix))]
    {
        candidate.is_file()
    }
}

fn pi_detection_paths(home: &Path) -> [PathBuf; 4] {
    [
        home.join(".pi").join("agent").join("bin").join("pi"),
        home.join(".local").join("bin").join("pi"),
        PathBuf::from("/opt/homebrew/bin/pi"),
        PathBuf::from("/usr/local/bin/pi"),
    ]
}

#[tauri::command]
pub fn pi_detect() -> bool {
    // GUI apps launched from /Applications inherit macOS's minimal default
    // PATH, not the user's shell PATH — mirrors `opencode_detect`'s reasoning
    // for why a $PATH-only scan isn't enough.
    let path_hit = std::env::var("PATH").is_ok_and(|path_var| {
        std::env::split_paths(&path_var).any(|dir| is_executable(&dir.join("pi")))
    });
    if path_hit {
        return true;
    }
    // Finder-launched apps do not inherit Homebrew's PATH either. Check its
    // standard prefixes as well as the per-user locations from Pi's official
    // installers.
    pi_detection_paths(Path::new(&home_or_tmp()))
        .iter()
        .any(|candidate| is_executable(candidate))
}

#[tauri::command]
pub fn pi_hooks_setup() -> Result<(), String> {
    fs::create_dir_all(extensions_dir()).map_err(|e| e.to_string())?;
    let path = extension_path();
    let existing = fs::read_to_string(&path).ok();
    let content = plan_setup(existing.as_deref())?;
    fs::write(path, content).map_err(|e| e.to_string())
}

#[tauri::command]
pub fn pi_hooks_remove() -> Result<(), String> {
    let path = extension_path();
    let existing = fs::read_to_string(&path).ok();
    if plan_remove(existing.as_deref())? {
        fs::remove_file(path).map_err(|e| e.to_string())?;
    }
    Ok(())
}

#[tauri::command]
pub fn pi_hooks_status() -> Result<bool, String> {
    Ok(fs::read_to_string(extension_path())
        .is_ok_and(|source| is_ours(&source) && has_current_version(&source)))
}

#[cfg(test)]
mod tests {
    use super::*;

    const FOREIGN: &str = "export default function (pi) { /* someone else's extension */ }\n";

    #[test]
    fn setup_on_absent_file_writes_owned_current_source() {
        let content = plan_setup(None).unwrap();
        assert!(is_ours(&content));
        assert!(has_current_version(&content));
    }

    #[test]
    fn setup_is_idempotent_on_an_owned_file() {
        let once = plan_setup(None).unwrap();
        let twice = plan_setup(Some(&once)).unwrap();
        assert_eq!(once, twice, "regenerating an owned file must be byte-identical");
    }

    #[test]
    fn setup_refuses_a_foreign_file_and_leaves_it_untouched() {
        assert!(plan_setup(Some(FOREIGN)).is_err());
    }

    #[test]
    fn remove_deletes_only_an_owned_file() {
        let owned = plan_setup(None).unwrap();
        assert_eq!(plan_remove(Some(&owned)), Ok(true));
    }

    #[test]
    fn remove_leaves_a_foreign_file_in_place() {
        assert!(plan_remove(Some(FOREIGN)).is_err());
    }

    #[test]
    fn remove_on_absent_file_is_a_noop() {
        assert_eq!(plan_remove(None), Ok(false));
    }

    #[test]
    fn status_true_only_for_current_owned_source() {
        assert!(!is_ours(FOREIGN));

        let stale = format!("// {MARKER} version 0\nexport default function (pi) {{}}\n");
        assert!(is_ours(&stale));
        assert!(!has_current_version(&stale));

        let current = extension_source();
        assert!(is_ours(&current));
        assert!(has_current_version(&current));
    }

    #[test]
    fn extension_source_embeds_marker_and_version() {
        let src = extension_source();
        assert!(src.contains(MARKER));
        assert!(src.contains(&format!("version {PI_EXTENSION_VERSION}")));
    }

    #[test]
    fn extension_source_embeds_the_ingest_contract() {
        let src = extension_source();
        assert!(src.contains("X-Logic-Loop-Tab"));
        assert!(src.contains("X-Logic-Loop-Agent\": \"pi"));
        assert!(src.contains("LOGIC_LOOP_TAB_ID"));
        assert!(src.contains("ingest.env"));
        assert!(src.contains("Authorization"));
    }

    #[test]
    fn extension_source_maps_the_six_events_and_nothing_else_to_stop() {
        let src = extension_source();
        assert!(src.contains("\"session_start\""));
        assert!(src.contains("\"before_agent_start\""));
        assert!(src.contains("\"message_end\""));
        assert!(src.contains("\"tool_execution_start\""));
        assert!(src.contains("\"tool_execution_end\""));
        assert!(src.contains("\"agent_settled\""));
        assert!(src.contains("\"session_shutdown\""));
        assert!(src.contains("hook_event_name: \"SessionStart\""));
        assert!(src.contains("hook_event_name: \"UserPromptSubmit\""));
        assert!(src.contains("hook_event_name: \"PostToolUse\""));
        assert!(src.contains("hook_event_name: \"Stop\""));
        // Only agent_settled may produce a Stop — agent_end/turn_end must
        // never be wired to anything in this file.
        assert!(!src.contains("agent_end"));
        assert!(!src.contains("turn_end"));
    }

    #[test]
    fn extension_source_forwards_only_visible_final_message_text() {
        let src = extension_source();
        assert!(src.contains("function visibleMessage(message)"));
        assert!(src.contains("message?.role !== \"user\" && message?.role !== \"assistant\""));
        assert!(src.contains("block?.type === \"text\""));
        assert!(src.contains("type: \"pi_message\""));
        assert!(src.contains("hook_event_name: \"TranscriptLine\""));
        assert!(!src.contains("event.prompt"));
        assert!(!src.contains("event.result"));
    }

    #[test]
    fn detection_paths_include_homebrew_prefixes() {
        let paths = pi_detection_paths(Path::new("/tmp/pi-home"));
        assert!(paths.contains(&PathBuf::from("/opt/homebrew/bin/pi")));
        assert!(paths.contains(&PathBuf::from("/usr/local/bin/pi")));
    }
}
